### ISSUE TITLE
Naming an organization in a self-evident way

### ISSUE THREAD

**Issue by theo-armour** [CDInstitute/CDInstitute.github.io#1]
@albertotono 
It's always nice when you see the name of an organization or the domain of a URL and you know what the organization does.

"Ministry of Health" and "Apple Computer" (as it used to be known before the phone) are name that come to mind.

At the other end of the spectrum, initials are easy to type. But they do get lost when search engine optimization is considered - and all the good URLs are usually taken.

Thinking out loud:

I had a quick look at what organization names are available on github and many suitable names are already taken. I see, however, that "ComputeDesign" is available.

I am also thinking about the word "Institute". It's a lovely word with a warm feeling on the other hand a little bit old school and very physical. In situations like this, I like to "stand on the shoulders of giants" and try and follow what wise people are doing.  So if GitHub call this thing we're doing an organization we could do this too.

Therefore "computedesign.org" would be possible (and may be available).

Any thoughts? You could pretend to start a new organization to try out other available names

**Comment by albertotono** [comment]
Thanks @theo-armour for your ideas. 

Ideally, it would be great to have CDI.edu but also CDI.org. The scope is educational and research focus like SFCDI, it will be important to preserve the history of the organization and keep the mission focus.

Another step will be to create the CD Foundation, that will support Open-Source Projects in the Design such as: 
- Ladybug
- Honeybee
- Blender
- Speckle
- Hypar
- Mission Control
- Spectacles
- and many others in different disciplines 

It will be fundamental to have a sort of graph as the ladybug one that you showed me yesterday but in 3d with the geolocalization of people. Let me know if you remember this company: https://3data.io/ it was at the meetup with Ricardo the first time we meet in 2018.

**Comment by theo-armour** [comment]
https://cdi.edu is already taken ;-(

***

Here are some 3D graphing projects I have worked on

* https://opentecture.github.io/mindmapping/graphql-3d/graphql-3d-r5.html
    * mouseover the blocks to see data in left menu
    * Not sure mouseover works on phone
* https://prediqtiv.github.io/eye-cue/replay/r3-1/eye-cue-replay-r3-1.html
* https://www.ladybug.tools/spider/cookbook/nurbs-chart/r3/nurbs-chart-random-numbers.html
* https://www.ladybug.tools/spider/cookbook/design-explorer-very-lite/r13/design-explorer-very-lite.html
* https://www.ladybug.tools/spider/cookbook/scatter-well/r1/index.html

**Comment by albertotono** [comment]
cd.institute
![image](https://user-images.githubusercontent.com/11828200/75100409-023ec900-5582-11ea-9b2c-ac9b3eca9384.png)

**Comment by theo-armour** [comment]
more choices and prices

https://domains.google.com/m/registrar/search?searchTerm=cdinstitute
